# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: postgresql
  encoding: unicode
  database: pgsierradatas # Nombre de la base de datos
  pool: 5
  username: fl0user # Nombre de usuario de PostgreSQL
  password: 2aSyvGgFP3ju # Contraseña de PostgreSQL
  host: ep-cool-cake-78432807.ap-southeast-1.aws.neon.tech # Host de la base de datos (puede ser localhost o la dirección IP del servidor de la base de datos)
  port: 5432 # Puerto de la base de datos (predeterminado para PostgreSQL es 5432)
  sslmode: require # Modo SSL (puede ser 'require', 'disable', etc., según tus necesidades)

test:
  adapter: postgresql
  encoding: unicode
  database: pgsierradatas # Nombre de la base de datos
  pool: 5
  username: fl0user # Nombre de usuario de PostgreSQL
  password: 2aSyvGgFP3ju # Contraseña de PostgreSQL
  host: ep-cool-cake-78432807.ap-southeast-1.aws.neon.tech # Host de la base de datos (puede ser localhost o la dirección IP del servidor de la base de datos)
  port: 5432 # Puerto de la base de datos (predeterminado para PostgreSQL es 5432)
  sslmode: require # Modo SSL (puede ser 'require', 'disable', etc., según tus necesidades)

production:
  adapter: postgresql
  encoding: unicode
  database: pgsierradatas # Nombre de la base de datos
  pool: 5
  username: fl0user # Nombre de usuario de PostgreSQL
  password: 2aSyvGgFP3ju # Contraseña de PostgreSQL
  host: ep-cool-cake-78432807.ap-southeast-1.aws.neon.tech # Host de la base de datos (puede ser localhost o la dirección IP del servidor de la base de datos)
  port: 5432 # Puerto de la base de datos (predeterminado para PostgreSQL es 5432)
  sslmode: require # Modo SSL (puede ser 'require', 'disable', etc., según tus necesidades)